### ISSUE TITLE
Invalid tree found. You must supply a path or an object with a `read` function.

### ISSUE THREAD

**Issue by vvs-code** [andybluntish/ember-cli-replace#4]
I have an app with ember-cli 0.1.15

I just add addon with 
``` npm install ember-cli-replace -S```

and even without any options ( and with options - the same ) I got en error on ember server start

```
 ~/repo/apollo-auth/ [test*] es
version: 0.1.15
Livereload server on port 35729
Serving on http://0.0.0.0:4200/
Invalid tree found. You must supply a path or an object with a `read` function.
Error: Invalid tree found. You must supply a path or an object with a `read` function.
  at readAndReturnNodeFor (/Users/vvs/repo/apollo-auth/node_modules/ember-cli/node_modules/broccoli/lib/builder.js:71:13)
  at /Users/vvs/repo/apollo-auth/node_modules/ember-cli/node_modules/broccoli/lib/builder.js:92:24
  at $$$internal$$tryCatch (/Users/vvs/repo/apollo-auth/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:490:16)
  at $$$internal$$invokeCallback (/Users/vvs/repo/apollo-auth/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:502:17)
  at /Users/vvs/repo/apollo-auth/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1096:13
  at $$rsvp$asap$$flush (/Users/vvs/repo/apollo-auth/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1581:9)
  at doNTCallback0 (node.js:408:9)
  at process._tickCallback (node.js:337:13)

^CCleanup error.
tree.cleanup is not a function
TypeError: tree.cleanup is not a function
  at cleanupTree (/Users/vvs/repo/apollo-auth/node_modules/ember-cli/node_modules/broccoli/lib/builder.js:128:19)
  at /Users/vvs/repo/apollo-auth/node_modules/ember-cli/node_modules/promise-map-series/index.js:11:14
  at $$$internal$$tryCatch (/Users/vvs/repo/apollo-auth/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:490:16)
  at $$$internal$$invokeCallback (/Users/vvs/repo/apollo-auth/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:502:17)
  at $$$internal$$publish (/Users/vvs/repo/apollo-auth/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:473:11)
  at $$rsvp$asap$$flush (/Users/vvs/repo/apollo-auth/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1581:9)
  at doNTCallback0 (node.js:408:9)
  at process._tickCallback (node.js:337:13)
```

ember -v shows
```
version: 0.1.15
node: 2.2.1
npm: 2.1.8
```

**Comment by andybluntish** [comment]
G'day,

I'm sorry, but I'm not sure I can be much help with this, since the version of Ember CLI you're using is quite old (currently up to 0.2.7) . Can you upgrade to a newer version and give that a go?

**Comment by vvs-code** [comment]
There I have trouble with another addon )) Issue already created - I'll write again when I'll update ember-cli

**Comment by vvs-code** [comment]
Works fine at 0.2.7

**Comment by andybluntish** [comment]
Excellent, great to hear!
